// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.6.1
// source: proto/covid_data.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CovidCasesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deaths     string `protobuf:"bytes,1,opt,name=Deaths,proto3" json:"Deaths,omitempty"`
	Country    string `protobuf:"bytes,2,opt,name=Country,proto3" json:"Country,omitempty"`
	Recovered  string `protobuf:"bytes,3,opt,name=Recovered,proto3" json:"Recovered,omitempty"`
	TotalCases string `protobuf:"bytes,4,opt,name=Total_cases,json=TotalCases,proto3" json:"Total_cases,omitempty"`
}

func (x *CovidCasesResponse) Reset() {
	*x = CovidCasesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_covid_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CovidCasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CovidCasesResponse) ProtoMessage() {}

func (x *CovidCasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_covid_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CovidCasesResponse.ProtoReflect.Descriptor instead.
func (*CovidCasesResponse) Descriptor() ([]byte, []int) {
	return file_proto_covid_data_proto_rawDescGZIP(), []int{0}
}

func (x *CovidCasesResponse) GetDeaths() string {
	if x != nil {
		return x.Deaths
	}
	return ""
}

func (x *CovidCasesResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CovidCasesResponse) GetRecovered() string {
	if x != nil {
		return x.Recovered
	}
	return ""
}

func (x *CovidCasesResponse) GetTotalCases() string {
	if x != nil {
		return x.TotalCases
	}
	return ""
}

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_covid_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_proto_covid_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_proto_covid_data_proto_rawDescGZIP(), []int{1}
}

var File_proto_covid_data_proto protoreflect.FileDescriptor

var file_proto_covid_data_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x76, 0x69, 0x64, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x85, 0x01, 0x0a,
	0x12, 0x43, 0x6f, 0x76, 0x69, 0x64, 0x43, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x61, 0x74, 0x68, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x65, 0x61, 0x74, 0x68, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x61, 0x73,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x61, 0x73, 0x65, 0x73, 0x22, 0x06, 0x0a, 0x04, 0x56, 0x6f, 0x69, 0x64, 0x32, 0x49, 0x0a, 0x0c,
	0x43, 0x6f, 0x76, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x76, 0x69, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x1a, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x76, 0x69, 0x64, 0x43, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_covid_data_proto_rawDescOnce sync.Once
	file_proto_covid_data_proto_rawDescData = file_proto_covid_data_proto_rawDesc
)

func file_proto_covid_data_proto_rawDescGZIP() []byte {
	file_proto_covid_data_proto_rawDescOnce.Do(func() {
		file_proto_covid_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_covid_data_proto_rawDescData)
	})
	return file_proto_covid_data_proto_rawDescData
}

var file_proto_covid_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_covid_data_proto_goTypes = []interface{}{
	(*CovidCasesResponse)(nil), // 0: pb.CovidCasesResponse
	(*Void)(nil),               // 1: pb.Void
}
var file_proto_covid_data_proto_depIdxs = []int32{
	1, // 0: pb.CovidService.GetCurrentCovidInfo:input_type -> pb.Void
	0, // 1: pb.CovidService.GetCurrentCovidInfo:output_type -> pb.CovidCasesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_covid_data_proto_init() }
func file_proto_covid_data_proto_init() {
	if File_proto_covid_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_covid_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CovidCasesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_covid_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_covid_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_covid_data_proto_goTypes,
		DependencyIndexes: file_proto_covid_data_proto_depIdxs,
		MessageInfos:      file_proto_covid_data_proto_msgTypes,
	}.Build()
	File_proto_covid_data_proto = out.File
	file_proto_covid_data_proto_rawDesc = nil
	file_proto_covid_data_proto_goTypes = nil
	file_proto_covid_data_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CovidServiceClient is the client API for CovidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CovidServiceClient interface {
	GetCurrentCovidInfo(ctx context.Context, in *Void, opts ...grpc.CallOption) (*CovidCasesResponse, error)
}

type covidServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCovidServiceClient(cc grpc.ClientConnInterface) CovidServiceClient {
	return &covidServiceClient{cc}
}

func (c *covidServiceClient) GetCurrentCovidInfo(ctx context.Context, in *Void, opts ...grpc.CallOption) (*CovidCasesResponse, error) {
	out := new(CovidCasesResponse)
	err := c.cc.Invoke(ctx, "/pb.CovidService/GetCurrentCovidInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CovidServiceServer is the server API for CovidService service.
type CovidServiceServer interface {
	GetCurrentCovidInfo(context.Context, *Void) (*CovidCasesResponse, error)
}

// UnimplementedCovidServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCovidServiceServer struct {
}

func (*UnimplementedCovidServiceServer) GetCurrentCovidInfo(context.Context, *Void) (*CovidCasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentCovidInfo not implemented")
}

func RegisterCovidServiceServer(s *grpc.Server, srv CovidServiceServer) {
	s.RegisterService(&_CovidService_serviceDesc, srv)
}

func _CovidService_GetCurrentCovidInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CovidServiceServer).GetCurrentCovidInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CovidService/GetCurrentCovidInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CovidServiceServer).GetCurrentCovidInfo(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _CovidService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CovidService",
	HandlerType: (*CovidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentCovidInfo",
			Handler:    _CovidService_GetCurrentCovidInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/covid_data.proto",
}
